export const TRAINER_REPOSITORY = 'TRAINER_REPOSITORY';
export const TEAM_REPOSITORY = 'TEAM_REPOSITORY';
export const POKEMON_REPOSITORY = 'POKEMON_REPOSITORY';
export const TEAM_POKEMON_REPOSITORY = 'TEAM_POKEMON_REPOSITORY';
export const VIACEP_SERVICE = 'VIACEP_SERVICE';
export const POKEAPI_SERVICE = 'POKEAPI_SERVICE';
